version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cars_db
    environment:
      POSTGRES_USER: cars_user
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: cars_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
